spring:
  application:
    name: spring-boot-demo-redis
  redis:
    host:
    port: 6379
    password:
    database: 13 # Redis默认情况下有16个分片，这里配置具体使用的分片
    timeout: 10000
#    cluster:
#      nodes:
#    sentinel:
#      master:
#      nodes:
    redisson:
      file: classpath:redisson.yaml
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
