spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: MyHikariCP
      primary: my-pg
      datasource:
        # mysql
        my-mysql:
          url: jdbc:mysql://192.168.50.237:3306/spring_boot_demo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useLocalSessionState=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        # postgres
        my-pg:
          url: jdbc:postgresql://192.168.50.237:5432/spring_boot_demo
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: postgres
#          hikari:
#            is-read-only: true # 开启只读

