server:
  port: 8080

spring:
  application:
    name: spring-boot-demo-dynamic-datasource
  main:
    # 关闭日志
    banner-mode: off
  profiles:
    active: dev
  # JPA 配置内容，对应 JpaProperties 类
  jpa:
    # 打印 SQL 。生产环境，建议关闭
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
#    properties:
#      # 不同数据的时候有点问题，暂时先关闭
#      hibernate:
#        # postgresql14的配置
#        pg-dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        # mysql的配置
#        mysql-dialect: org.hibernate.dialect.MySQL8Dialect

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.remember.dynamic.datasource
  global-config:
    # 数据库相关配置
    db-config:
      #驼峰下划线转换
      table-underline: true
      #是否开启大写命名，默认不开启
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
