server:
  port: 8080
spring:
  # redis configuration
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 9 # Redis默认情况下有16个分片，这里配置具体使用的分片
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  # rabbitmq configuration
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# netty websocket configuration
web-socket:
  enable-cluster: true
  netty:
    port: 58080
    path: /ws
    backlog: 1024
