server:
  port: 9902

spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:9900
        instance:
          # 客户端实例 url
          service-url: http://127.0.0.1:9902
          prefer-ip: true
          # 客户端实例名称
          name: admin-client2

management:
  endpoints:
    web:
      exposure:
        # 暴漏的接口 - 所有接口
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS