server:
  port: 9092

spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true # 打印 SQL 。生产环境，建议关闭
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: postgres
    # HikariCP 自定义配置，对应 HikariConfig 配置属性类
    hikari:
      minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
