### 本地发送给指定用户
POST http://localhost:8080/push/localPush2User

{
  "userId": "xyz"
  "message": "我是发送给所有人的消息"
}



### 本地发送给所有用户
POST http://localhost:8080/push/localPushAllUser

{
  "message": "我是发送给所有人的消息"
}



### 发送给指定用户
POST http://localhost:8080/push/pushMsg2User

{
  "userId": "xyz"
  "message": "我是发送给所有人的消息"
}



### 发送给所有用户
POST http://localhost:8080/push/pushMsg2AllUser

{
  "message": "我是发送给所有人的消息"
}
