server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 9 # Redis默认情况下有16个分片，这里配置具体使用的分片
    lettuce:
      pool:
        min-idle: 10  # 连接池中的最小空闲连接 默认 0
        max-idle: 1000 # 连接池中的最大空闲连接 默认 8
        max-active: 10000 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 5000ms  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
    timeout: 0ms # 连接超时时间（记得添加单位，Duration）

web-socket:
  enable-cluster: true
  netty:
    port: 58080
    path: /ws
    backlog: 1024
