/**
 * Copyright [2022] [remember5]
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.remember5.db2doc.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.remember5.db2doc.entity.DbDTO;
import com.remember5.db2doc.utils.Db2DocUtils;
import lombok.Data;

import javax.swing.*;
import java.io.File;

/**
 * @author wangjiahao
 * @date 2023/8/29 16:48
 */
@Data
public class MyGUI extends JFrame {
    private JPanel fdsa;
    private JTextField ip;
    private JTextField port;
    private JTextField username;
    private JTextField password;
    private JTextField database;
    private JComboBox generateType;
    private JComboBox dbType;
    private JButton generateButton;

    public MyGUI() {
        generateButton.addActionListener(e -> {
            DbDTO dbDto = new DbDTO();
            dbDto.setDbType(dbType.getSelectedItem().toString());
            dbDto.setIp(ip.getText());
            dbDto.setPort(Integer.parseInt(port.getText()));
            dbDto.setUsername(username.getText());
            dbDto.setPassword(password.getText());
            dbDto.setDatabase(database.getText());
            dbDto.setGenerateType(generateType.getSelectedItem().toString());


            JFileChooser fileChooser = new JFileChooser();
            // 打开文件夹选择对话框
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            // Open the save dialog
            int result = fileChooser.showSaveDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                // 用户选择了文件夹
                // 获取用户选择的文件夹路径
                File selectedDir = fileChooser.getSelectedFile();
                String dirPath = selectedDir.getAbsolutePath();
                System.out.println("选择的文件夹路径：" + dirPath);
                dbDto.setFileOutputDir(dirPath);
                Db2DocUtils.generatedDoc(dbDto);
                JOptionPane.showMessageDialog(fdsa, "已生成！", "提示", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        fdsa = new JPanel();
        fdsa.setLayout(new FormLayout("center:75px:noGrow,left:6dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("IP");
        CellConstraints cc = new CellConstraints();
        fdsa.add(label1, cc.xy(1, 5));
        ip = new JTextField();
        fdsa.add(ip, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Port");
        fdsa.add(label2, cc.xy(1, 7));
        port = new JTextField();
        fdsa.add(port, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setText("Username");
        fdsa.add(label3, cc.xy(1, 9));
        username = new JTextField();
        fdsa.add(username, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label4 = new JLabel();
        label4.setText("Password");
        fdsa.add(label4, cc.xy(1, 11));
        password = new JTextField();
        fdsa.add(password, cc.xy(3, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        label5.setText("Datebase");
        fdsa.add(label5, cc.xy(1, 13));
        database = new JTextField();
        fdsa.add(database, cc.xy(3, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label6 = new JLabel();
        label6.setText("生成类型");
        fdsa.add(label6, cc.xy(1, 15));
        generateType = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        generateType.setModel(defaultComboBoxModel1);
        fdsa.add(generateType, cc.xy(3, 15));
        final JLabel label7 = new JLabel();
        label7.setText("数据库类型");
        fdsa.add(label7, cc.xy(1, 3));
        dbType = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        dbType.setModel(defaultComboBoxModel2);
        fdsa.add(dbType, cc.xy(3, 3));
        generateButton = new JButton();
        generateButton.setText("生成");
        fdsa.add(generateButton, cc.xy(3, 17));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return fdsa;
    }
}
